version: "3.8"
services:

#  api:
#    container_name: api
#    build: .
#    ports:
#      - 8080:8080

  postgresql:
    container_name: postgres
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sqlhaslo
      POSTGRES_USER: postgres
      POSTGRES_DB: sqlbaza
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: sqlhaslo

volumes:
  postgres: