ALTER TABLE DELEGATION
    ADD COLUMN COUNTRY VARCHAR(255) NOT NULL,
    ADD COLUMN CITY VARCHAR(255) NOT NULL;

UPDATE DELEGATION

SET COUNTRY = TRIM (LEADING FROM split_part(DELEGATION.LOCATION, ',', 2)),
    CITY =split_part(DELEGATION.LOCATION, ',', 1);

ALTER TABLE DELEGATION
DROP COLUMN LOCATION;