ALTER TABLE DELEGATION
    ADD COUNTRY VARCHAR(255)
    ADD CITY VARCHAR(255);

UPDATE DELEGATION
SET COUNTRY =split_part(DELEGATION.LOCATION, ',', 2) , CITY =split_part(DELEGATION.LOCATION, ',', 1);

ALTER TABLE DELEGATION
DROP COLUMN LOCATION;